# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Test compilation
        run: gcc crypt_demo.c -o crypt_demo -lpthread -lcrypt

      - name: Test crypt library
        run: ./crypt_demo na apple

      - name: Compile crack.c
        run: gcc crack.c -o crack -lpthread -lcrypt

      - name: Reverse hash for "cat" and salt "na"
        run: ./autograder.sh 1 3 nah75fZUVChm. cat
        
      - name: Reverse hash for "dog" and salt "na"
        run: ./autograder.sh 1 3 naVKWk9bmVEUU dog

      - name: Reverse hash for "dog" and salt "xy"
        run: ./autograder.sh 1 3 xyFiMGmVQB5aE dog

      - name: Reverse hash for "apple" and salt "na"
        run: ./autograder.sh 1 5 na3C5487Wz4zw apple

      #- name: Searches for password length 3 with keysize 4
      #  run: ./autograder.sh 1 4 nah75fZUVChm. cat

      - name: Searches for password of length 1
        run: ./autograder.sh 1 1 nax/0Vd3n1O2w x

      - name: Search time for keysize=4 and threads=1
        run: time ./crack 1 4 nomatchinghash

      - name: Search time for keysize=4 and threads=2
        run: time ./crack 2 4 nomatchinghash

      - name: Search time for keysize=4 and threads=4
        run: time ./crack 4 4 nomatchinghash
      
